
# cooldown is in seconds
# material must be a valid Minecraft item
healing:
  - material: blue_dye
    hearts-gained: 2.5
    waiting-time: 1.2
  - material: red_dye
    hearts-gained: 5
    waiting-time: 2.1

kits:
  - name:
    items:
    slot:

