# PLEASE READ BEFORE MODIFYING HEALING:
# -please follow the format given by the default config (very important)
# -cooldown is in seconds
# -material must be a valid Minecraft item (i.e., cooked_beef is valid but steak is not)
# -you can add more things to the list as long as you follow the formatting
healing:
  - material: blue_dye
    hearts-gained: 2.5
    waiting-time: 1.2
  - material: red_dye
    hearts-gained: 5
    waiting-time: 2.1

# PLEASE READ BEFORE MODIFYING KITS:
# -please follow the format given by the default config (very important)
# -cooldown is in hours
# -all items must be valid Minecraft items (i.e., cooked_beef is valid but steak is not)
# -you can add more things to the lists as long as you follow the formatting
kits:
  - name: Iron Defender
    representative-item: iron_block
    slot: 0
    items:
      - name: iron_sword
        quantity: 1
      - name: shield
        quantity: 1
      - name: bread
        quantity: 32
    armor:
      - iron_helmet
      - iron_chestplate
      - iron_leggings
      - iron_boots
    cooldown: 0.05

  - name: Gold Archer
    representative-item: gold_block
    slot: 1
    items:
      - name: golden_sword
        quantity: 1
      - name: bow
        quantity: 1
      - name: arrow
        quantity: 64
    armor:
      - golden_helmet
      - golden_chestplate
      - golden_leggings
      - golden_boots
    cooldown: 4.2

  - name: Leather Scout
    representative-item: leather
    slot: 2
    items:
      - name: wooden_sword
        quantity: 1
      - name: compass
        quantity: 1
      - name: cooked_porkchop
        quantity: 16
    armor:
      - leather_helmet
      - leather_chestplate
      - leather_leggings
      - leather_boots
    cooldown: 1.5

  - name: Emerald Mage
    representative-item: emerald
    slot: 3
    items:
      - name: enchanted_book
        quantity: 1
      - name: potion
        quantity: 3
      - name: bread
        quantity: 16
    armor:
      - diamond_chestplate
    cooldown: 3.0

  - name: Nether Warrior
    representative-item: nether_brick
    slot: 4
    items:
      - name: netherite_sword
        quantity: 1
      - name: crossbow
        quantity: 1
      - name: cooked_beef
        quantity: 32
    armor:
      - netherite_helmet
      - netherite_chestplate
      - netherite_leggings
      - netherite_boots
    cooldown: 5.0

  - name: Ender Slayer
    representative-item: end_stone
    slot: 5
    items:
      - name: diamond_sword
        quantity: 1
      - name: ender_pearl
        quantity: 5
      - name: cooked_beef
        quantity: 16
    armor:
      - diamond_helmet
      - diamond_chestplate
      - diamond_leggings
      - diamond_boots
    cooldown: 4.0

  - name: Snow Warrior
    representative-item: snow_block
    slot: 6
    items:
      - name: iron_sword
        quantity: 1
      - name: snowball
        quantity: 32
      - name: carrot
        quantity: 16
    armor:
      - iron_helmet
      - iron_chestplate
      - iron_leggings
      - iron_boots
    cooldown: 2.5

  - name: Jungle Explorer
    representative-item: melon
    slot: 7
    items:
      - name: stone_sword
        quantity: 1
      - name: shears
        quantity: 1
      - name: apple
        quantity: 16
    armor:
      - leather_helmet
      - leather_chestplate
      - leather_leggings
      - leather_boots
    cooldown: 1.8

  - name: Desert Nomad
    representative-item: sand
    slot: 8
    items:
      - name: wooden_sword
        quantity: 1
      - name: map
        quantity: 1
      - name: dried_kelp
        quantity: 32
    armor:
      - chainmail_helmet
      - chainmail_chestplate
      - chainmail_leggings
      - chainmail_boots
    cooldown: 3.5

  - name: Oceanic Guardian
    representative-item: prismarine
    slot: 9
    items:
      - name: trident
        quantity: 1
      - name: cooked_beef
        quantity: 16
    armor:
      - diamond_helmet
      - diamond_chestplate
      - diamond_leggings
      - diamond_boots
    cooldown: 4.5

  - name: Forest Ranger
    representative-item: oak_log
    slot: 10
    items:
      - name: stone_axe
        quantity: 1
      - name: bow
        quantity: 1
      - name: cookie
        quantity: 16
    armor:
      - leather_helmet
      - leather_chestplate
      - leather_leggings
      - leather_boots
    cooldown: 2.0

  - name: Cavern Crawler
    representative-item: coal
    slot: 11
    items:
      - name: iron_pickaxe
        quantity: 1
      - name: torch
        quantity: 64
      - name: bread
        quantity: 16
    armor:
      - iron_helmet
      - iron_chestplate
      - iron_leggings
      - iron_boots
    cooldown: 2.2

  - name: Volcano Fighter
    representative-item: magma_block
    slot: 12
    items:
      - name: diamond_sword
        quantity: 1
      - name: fire_charge
        quantity: 10
      - name: cooked_beef
        quantity: 16
    armor:
      - diamond_helmet
      - diamond_chestplate
      - diamond_leggings
      - diamond_boots
    cooldown: 5.5

  - name: Sky Knight
    representative-item: blue_ice
    slot: 13
    items:
      - name: diamond_sword
        quantity: 1
      - name: elytra
        quantity: 1
      - name: golden_carrot
        quantity: 16
    armor:
      - diamond_helmet
      - diamond_chestplate
      - diamond_leggings
      - diamond_boots
    cooldown: 6.0

  - name: Shadow Assassin
    representative-item: obsidian
    slot: 14
    items:
      - name: netherite_sword
        quantity: 1
      - name: cooked_beef
        quantity: 16
    armor:
      - netherite_helmet
      - netherite_chestplate
      - netherite_leggings
      - netherite_boots
    cooldown: 4.8

  - name: Lunar Guardian
    representative-item: glowstone
    slot: 15
    items:
      - name: diamond_sword
        quantity: 1
      - name: cobblestone
        quantity: 5
      - name: apple
        quantity: 16
    armor:
      - diamond_helmet
      - diamond_chestplate
      - diamond_leggings
      - diamond_boots
    cooldown: 3.5

  - name: Pirate Captain
    representative-item: emerald
    slot: 16
    items:
      - name: golden_sword
        quantity: 1
      - name: compass
        quantity: 1
      - name: cooked_beef
        quantity: 16
    armor:
      - golden_helmet
      - golden_chestplate
      - golden_leggings
      - golden_boots
    cooldown: 3.8

  - name: Alchemist
    representative-item: brewing_stand
    slot: 17
    items:
      - name: potion
        quantity: 5
      - name: glass_bottle
        quantity: 3
      - name: bread
        quantity: 16
    armor:
      - leather_helmet
      - leather_chestplate
      - leather_leggings
      - leather_boots
    cooldown: 2.7

  - name: Forest Sentinel
    representative-item: oak_log
    slot: 18
    items:
      - name: wooden_sword
        quantity: 1
      - name: oak_sapling
        quantity: 5
      - name: cookie
        quantity: 16
    armor:
      - leather_helmet
      - leather_chestplate
      - leather_leggings
      - leather_boots

  - name: Arcane Warrior
    representative-item: lapis_block
    slot: 19
    items:
      - name: diamond_sword
        quantity: 1
      - name: potion
        quantity: 3
      - name: bread
        quantity: 16
    armor:
      - diamond_helmet
      - diamond_chestplate
      - diamond_leggings
      - diamond_boots

  - name: Mountain Warrior
    representative-item: cobblestone
    slot: 20
    items:
      - name: iron_axe
        quantity: 1
      - name: cooked_beef
        quantity: 16
      - name: torch
        quantity: 32
    armor:
      - iron_helmet
      - iron_chestplate
      - iron_leggings
      - iron_boots
