
# cooldown is in seconds
# material must be a valid Minecraft item
healing:
  - material: blue_dye
    hearts-gained: 2.5
    waiting-time: 1.2
  - material: red_dye
    hearts-gained: 5
    waiting-time: 2.1

custom-items:
  - bababooey

kits:
  - name: Diamond Warrior
    representative-item: diamond_block
    slot: 4
    items:
      - name: diamond_sword
        quantity: 1
      - name: bow
        quantity: 1
      - name: arrow
        quantity: 64
    armor:
      - diamond_helmet
      - diamond_chestplate
      - diamond_leggings
      - diamond_boots



