name: ZombieGame
version: '${project.version}'
main: me.cfstar188.zombiegame.ZombieGame
api-version: '1.20'
softdepend: [WeaponMechanics, MechanicsCore, ProtocolLib]
commands:
  kits:
    description: Open the kit menu
    usage: /kits
    aliases:
      - kit
  givecurrency:
    description: Gives the player the specified amount of currency
    usage: /givecurrency <player> <amount>
    aliases:
      - givemoney
  removecurrency:
    description: Takes he specified amount of currency from the player
    usage: /removecurrency <player> <amount>
    aliases:
      - takecurrency
      - takemoney
      - removemoney
  givecustom:
    description: Gives a custom item or armor piece to the specified player
    usage: /givecustom <player> <item> <amount>